### PR TITLE
Move to project ids instead of names

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Move to use project ids instead of project names as these are domain scoped and fix the _rescope function to properly work with recent keystoneauth1. It also uses URL of Keystone instead of nova's to avoid having duplicated entries.

### CODE REVIEW

**Comment by enolfc** [comment]
Build fixed. 

Now realised that it's not clear to me if the changes related to keystoneauth may break in older versions !?

Do we have a minimum OpenStack target for this so we can take the exact version and test?

**Comment by enolfc** [comment]
Do not merge yet, I'm testing with real provider

**Comment by gwarf** [comment]
I think we should test with the versions being packaged by default for CentOS 7 and something like Ubuntu LTS supporting mitaka. We can refer to https://wiki.egi.eu/wiki/Federated_Cloud_infrastructure_status to see what is available in our infra.
We don't have clear versions I think, we just said that we would deprecate v2.0.

**Comment by gwarf** [comment]
Supersed by #4

**Pull request closed without merging**
