### PR TITLE
Glue1.2 for OpenStack

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

This change makes sure that the provider is still able to render Glue1.2 information for OpenStack as before the big merge.

----

### CODE REVIEW

**Comment by enolfc** [comment]
as usual tests fail :P, will fix soon

**Comment by enolfc** [comment]
One thing to consider: this works using the new configuration file! Older config will just crash. Should we try to support that too?

**Comment by gwarf** [comment]
Can you please rebase @enolfc ?

**Comment by enolfc** [comment]
mmm, this is already merged by the other PR 😛 
Closing it.

**Pull request closed without merging**
